### ISSUE TITLE
NumpadEnter

### ISSUE THREAD

**Issue by buschtoens** [patience-tema-baron/ember-keyboard#80]
Presumably the switch from jQuery to native events bricked the `NumpadEnter` key.

Previously `keyDown('Enter')` captured both, the regular `Enter` and the `NumpadEnter`.

**Comment by patience-tema-baron** [comment]
Thanks for reporting, @buschtoens. I've confirmed that the behavior changed from `2.3.0` -> `3.0.0`, though I'm at a loss for what exactly caused the change. My first thought was that jQuery had creating some sort of abstract `Enter`, but a cursory search through its codebase isn't turning up anything like that.

My thoughts are that we should let it be, rather than creating some abstract `Enter` of our own. It keeps the code simpler, and it also allows us to now specify `Enter` and `NumpadEnter` separately, when necessary. Though obviously, this comes at the cost of having to specify both when you want to handle both, which is probably the more common scenario.

What our your thoughts?

**Comment by NoodleSkadoodle** [comment]
@patience-tema-baron  Seperating Enter and NumpadEnter is fine, but right now using NumpadEnter also outputs the following in console:
> `NumpadEnter` is not a valid key name

https://github.com/patience-tema-baron/ember-keyboard/blob/e470114be9b70a3b20caa3547004776604c2b748/addon/listeners/key-events.js#L12 , NumpadEnter is not in validKeys. It still functions, but is rather confusing.

**Comment by patience-tema-baron** [comment]
Thanks for the update, @NoodleSkadoodle. I'll have a fix out this weekend.

**Comment by patience-tema-baron** [comment]
Fixed in `v3.0.2`. Thanks, @NoodleSkadoodle
